name: Prettier Formatting

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - staging

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install frontend dependencies
              run: |
                  npm install

            - name: Check frontend code
              run: |
                  npx prettier --check .
